import { Student } from './pdf-utils'

// Mock data for development
export const mockStudents: Student[] = [
  {
    id: '1',
    name: 'Akshada Prakash Takwale',
    age: 19,
    class: '1st Year College',
    village: 'Kondhur',
    school: 'Abhinav College Narhe Ambegaon',
    currentEducation: 'MSc Information Technology',
    academicPerformance: {
      year1: '2022, 10th Standard, 69.60%',
      year2: '2023, 11th Standard, 49.00%',
      year3: '2024, 12th Standard, 42.00%'
    },
    achievements: 'District level athletics third rank, School topper in Computer Science',
    futurePlans: 'Police Officer in Maharashtra Police',
    disability: 'None',
    fatherName: 'Prakash Takwale',
    motherName: 'Vaishali Takwale',
    parentAge: '40 & 35 years',
    parentEducation: 'Standard 10th both parents',
    totalFamilyMembers: 6,
    earningMembers: 1,
    phone: '9022704532',
    address: 'Kondhur Digewadi, Taluka Mulshi, District Pune, Maharashtra 412108',
    status: 'approved',
    expenses: {
      travel: 1000,
      fees: 15000,
      books: 2000,
      stationery: 3000,
      uniform: 1500,
      tuition: 10000,
      other: 2000
    },
    totalExpenses: 34500,
    familyIncome: 35000,
    incomeSource: 'Agriculture and Farming',
    expenseBearer: 'Parents',
    needsHelp: 'Yes',
    submissionDate: '2025-01-15'
  },
  {
    id: '2',
    name: 'Vaishnavi Prakash Takwale',
    age: 18,
    class: '1st Year College',
    village: 'Kondhur',
    school: 'Abhinav College Narhe Ambegaon',
    currentEducation: 'Diploma in Tally and Accounting',
    academicPerformance: {
      year1: '2022, 10th Standard, 72.00%',
      year2: '2023, 11th Standard, 47.00%',
      year3: '2024, 12th Standard, 49.50%'
    },
    achievements: 'Best student in Commerce stream, Participated in state level debate competition',
    futurePlans: 'Bank Manager in Cooperative Bank',
    disability: 'None',
    fatherName: 'Prakash Takwale',
    motherName: 'Vaishali Takwale',
    parentAge: '40 & 35 years',
    parentEducation: 'Standard 10th both parents',
    totalFamilyMembers: 6,
    earningMembers: 1,
    phone: '9022704532',
    address: 'Kondhur Digewadi, Taluka Mulshi, District Pune, Maharashtra 412108',
    status: 'pending',
    expenses: {
      travel: 1000,
      fees: 20000,
      books: 2000,
      stationery: 1500,
      uniform: 1000,
      tuition: 10000,
      other: 500
    },
    totalExpenses: 36000,
    familyIncome: 35000,
    incomeSource: 'Agriculture and Farming',
    expenseBearer: 'Parents',
    needsHelp: 'Yes',
    submissionDate: '2025-01-20'
  },
  {
    id: '3',
    name: 'Komal Prakash Salunke',
    age: 16,
    class: '11th Standard',
    village: 'Wanjale',
    school: 'MES Abasaheb Garware College',
    currentEducation: '11th Science (PCB)',
    academicPerformance: {
      year1: '2023, 9th Standard, 78.00%',
      year2: '2024, 10th Standard, 82.50%',
      year3: '2025, 11th Standard, Ongoing'
    },
    achievements: 'School Science Exhibition winner, District level drawing competition second prize',
    futurePlans: 'Doctor (MBBS) and serve rural areas',
    disability: 'None',
    fatherName: 'Prakash Salunke',
    motherName: 'Sunita Salunke',
    parentAge: '45 & 42 years',
    parentEducation: 'Father: 12th Standard, Mother: 10th Standard',
    totalFamilyMembers: 5,
    earningMembers: 2,
    phone: '7391858935',
    address: 'Wanjale Village, Taluka Mulshi, District Pune, Maharashtra 412115',
    status: 'approved',
    expenses: {
      travel: 2000,
      fees: 8000,
      books: 3000,
      stationery: 1500,
      uniform: 2000,
      tuition: 12000,
      other: 1500
    },
    totalExpenses: 30000,
    familyIncome: 48000,
    incomeSource: 'Agriculture and Small Business',
    expenseBearer: 'Parents',
    needsHelp: 'Yes',
    submissionDate: '2025-01-25'
  },
  {
    id: '4',
    name: 'Rahul Ganesh Patil',
    age: 20,
    class: '2nd Year College',
    village: 'Shivapur',
    school: 'Fergusson College Pune',
    currentEducation: 'BSc Computer Science',
    academicPerformance: {
      year1: '2021, 10th Standard, 85.20%',
      year2: '2022, 11th Standard, 72.00%',
      year3: '2023, 12th Standard, 78.50%'
    },
    achievements: 'College programming contest winner, Internship at local IT company',
    futurePlans: 'Software Developer in multinational company',
    disability: 'None',
    fatherName: 'Ganesh Patil',
    motherName: 'Mangala Patil',
    parentAge: '48 & 44 years',
    parentEducation: 'Father: 10th Standard, Mother: 8th Standard',
    totalFamilyMembers: 4,
    earningMembers: 1,
    phone: '9876543210',
    address: 'Shivapur Village, Taluka Mulshi, District Pune, Maharashtra 412112',
    status: 'approved',
    expenses: {
      travel: 1500,
      fees: 25000,
      books: 4000,
      stationery: 2000,
      uniform: 0,
      tuition: 15000,
      other: 2500
    },
    totalExpenses: 50000,
    familyIncome: 42000,
    incomeSource: 'Daily Labor and Agriculture',
    expenseBearer: 'Parents and Self (Part-time work)',
    needsHelp: 'Yes',
    submissionDate: '2025-02-01'
  },
  {
    id: '5',
    name: 'Sneha Ramesh Jadhav',
    age: 18,
    class: '1st Year College',
    village: 'Karjat',
    school: 'Modern College Pune',
    currentEducation: 'BCom (Bachelor of Commerce)',
    academicPerformance: {
      year1: '2022, 10th Standard, 74.80%',
      year2: '2023, 11th Standard, 58.00%',
      year3: '2024, 12th Standard, 61.20%'
    },
    achievements: 'Best student award in Commerce, Active member of college cultural committee',
    futurePlans: 'Bank Officer in nationalized bank',
    disability: 'None',
    fatherName: 'Ramesh Jadhav',
    motherName: 'Kavita Jadhav',
    parentAge: '43 & 39 years',
    parentEducation: 'Father: 12th Standard, Mother: 10th Standard',
    totalFamilyMembers: 4,
    earningMembers: 2,
    phone: '9988776655',
    address: 'Karjat Village, Taluka Mulshi, District Pune, Maharashtra 412117',
    status: 'pending',
    expenses: {
      travel: 900,
      fees: 12000,
      books: 1800,
      stationery: 2200,
      uniform: 1300,
      tuition: 9000,
      other: 800
    },
    totalExpenses: 28000,
    familyIncome: 55000,
    incomeSource: 'Small Business and Agriculture',
    expenseBearer: 'Parents',
    needsHelp: 'Yes',
    submissionDate: '2025-02-05'
  },
  {
    id: '6',
    name: 'Amit Vijay Kale',
    age: 16,
    class: '11th Standard',
    village: 'Kondhur',
    school: 'Zilla Parishad High School',
    currentEducation: '11th Commerce',
    academicPerformance: {
      year1: '2023, 9th Standard, 68.40%',
      year2: '2024, 10th Standard, 71.20%',
      year3: '2025, 11th Standard, Ongoing'
    },
    achievements: 'Sports captain of school cricket team, District level cricket player',
    futurePlans: 'Chartered Accountant (CA)',
    disability: 'None',
    fatherName: 'Vijay Kale',
    motherName: 'Sushila Kale',
    parentAge: '38 & 35 years',
    parentEducation: 'Both parents: 10th Standard',
    totalFamilyMembers: 5,
    earningMembers: 1,
    phone: '9112233445',
    address: 'Kondhur Village, Taluka Mulshi, District Pune, Maharashtra 412108',
    status: 'rejected',
    expenses: {
      travel: 600,
      fees: 6000,
      books: 1200,
      stationery: 1500,
      uniform: 1000,
      tuition: 5000,
      other: 700
    },
    totalExpenses: 16000,
    familyIncome: 30000,
    incomeSource: 'Agriculture and Seasonal Work',
    expenseBearer: 'Parents',
    needsHelp: 'Yes',
    submissionDate: '2025-02-10'
  }
]